#!/bin/bash
set -e

if [ "$#" -eq 0 ]; then
    echo "cleanup_failed_feat_dirs expects the base directory containing .feat directories to examine."
    exit 1
fi

rmforce=
if [ "$#" -eq 2 ]; then
    [ "$1" = "-f" ] && rmforce=y || (echo "don't know how to interpret $1" && exit 1)
    basedir="${2}"
else
    basedir="${1}"
fi

l1featdirs=$( find "$basedir" -iname "*.feat" -type d )

#l1 checks (still running)
for f in ${l1featdirs}; do
    if [ -f ${f}/report.html ]; then
	#for L1, either an error or a message of "STILL RUNNING" would count as problematic
	grep -q "Error" ${f}/report.html && errors=1 || errors=0
	grep -q "STILL RUNNING" ${f}/report.html && errors=1
	if [ $errors -eq 1 ]; then
	    echo "FEAT directory listed as having errors or STILL RUNNING: ${f}"
	    rmproceed=$rmforce
	    until [[ "$rmproceed" = [NnYy] ]]; do
		read -sn1 -p "  Delete? (y/n)" rmproceed
	    done

	    #rmproceed=y
	    if [[ "$rmproceed" == "Y" || "$rmproceed" == "y" ]]; then
		echo "  Now deleting $f"
		rm -rf "${f}"
	    fi
	fi	    
    fi
done

l2featdirs=$( find "$basedir" -iname "*.gfeat" -type d )
for f in ${l2featdirs}; do
    if [ -f ${f}/report.html ]; then
	#grep -q "Errors occured during the analysis" ${f}/report.html && errors=1 || errors=0
	grep -q "Error" ${f}/report.html && errors=1 || errors=0
	grep -q "STILL RUNNING" ${f}/report.html && errors=1
	if [ $errors -eq 1 ]; then
	    echo "GFEAT directory listed as having errors of STILL RUNNING: ${f}"
	    rmproceed=$rmforce
	    until [[ "$rmproceed" = [NnYy] ]]; do
		read -sn1 -p "  Delete? (y/n)" rmproceed
	    done

	    if [[ "$rmproceed" == "Y" || "$rmproceed" == "y" ]]; then
		echo "  Now deleting $f"
		rm -rf "${f}"
	    fi
	fi	    
    fi
done

