#!/usr/bin/env bash
set -eo pipefail
trap 'e=$?; [ $e -ne 0 ] && echo "$0 exited in error"' EXIT

#
#  quickly test out gre fieldmap configurations
#  for older siemens protocols.
#  newer (2021+) should probably be using spin echo for distortion correction
#  20201228WF  init

scriptDir="$(dirname $0)"
source "${scriptDir}/preproc_functions/helper_functions"
source "${scriptDir}/preproc_functions/prepare_fieldmap"
source "${scriptDir}/preproc_functions/prepare_gre_fieldmap"
source "${scriptDir}/preproc_functions/register_func2struct"
source "${scriptDir}/preproc_functions/prepare_mc_target"
source "${scriptDir}/preproc_functions/fast_wmseg"

# FM_ - fieldmap space
# EF_ - epi space 
#
# _D   - distorted (origianl)
# _UD  - undistored (corrected)

fm_cfg=; epi=; mag=; phase=;
# initialize vars allowed to be none
fmap_struct_dof=bbr
mprage_bet=""
savedir=""

usage(){
   # usage extracted from source
   # match -OPT) .... # DESCRIPTON
   # and spit out for documentation
   echo -e "$(basename $0) USAGE: "
   perl -lne '
    BEGIN{$_=<> until /^\s*#DOCSTART/}
    exit if /^\s*#DOCSTOP/;
    print "  $1\t$3" if /(-.*?)(\)|\|).*?#(.*)/' $0|
       column -ts$'\t'
    exit
}

while [ $# -gt 0 ]; do
   #DOCSTART -- options parsed by perl oneliner in usage()
   case "$1" in
      -help|-usage|-h) usage;; # usage
      -cfg) fm_cfg="$2"; shift 2;; # fieldmap configuration file (includes TEdiff, unwarpdir, ..)
      -epi) epi="$2"; shift 2;;    # epi to undistort (one volume, e.g. mc_target.nii.gz)
      -mag) mag="$2"; shift 2;;    # magnitude nifti (e.g. fmap/magintude1.nii.gz)
      -phase) phase="$2"; shift 2;; # phase nifti (e.g. fmap/phase.nii.gz)
      -mprage_bet) mprage_bet="$2"; shift 2;; # optional: structural to use for warping. (longer to run)
      -quick) mprage_bet=""; shift;; # optional: remove mprage_bet if specified earlier. order dependent.
      -savedir) savedir="$2"; shift 2;; # optional: folder to save everything (otherwise us fm_cfg name)
      -nobbr) fmap_struct_dof=6; shift ;; #optional: disable bbr. use 6 dof warp instead
      *) echo "unknown option '$1', see -help!"; exit 1;;
   esac
   #DOCSTOP
done

[ -z "$fm_cfg" ] && echo "must have -cfg" && exit 1
[ -z "$savedir" ] && savedir=fmcfg-$(basename $fm_cfg)

# check paths and make absolute
for var in epi mag phase mprage_bet fm_cfg; do
   [ -z "${!var}" ] && continue
   [ ! -s "${!var}" ] && echo "$var '${!var}' does not exist or is zero size!" && exit 1
   printf -v "$var" "$(realpath ${!var})"
done

source $fm_cfg
[ -z "$dwelltime" ] && echo "'$fm_cfg' is missing 'dwelltime'" && exit 1

[ ! -d $savedir ] && mkdir $savedir

cd $savedir
savedir=$(pwd)

# globals from preprocessFunctional
logFile="$savedir/main.log" # no logging
funcdir="$savedir"
qa_imgdir="$savedir/qa"; test -d $qa_imgdir || mkdir $_
qa_imglog="$savedir/qa/img.log"
#fm_phasedir=$(pwd) DISTORTION_DIR=""
bbrCapable=1
use_ants=1
ext=.nii.gz
use_fm=1
export FIELDMAP_TRANSFORMS_DIR="$savedir/transforms"
test ! -d $FIELDMAP_TRANSFORMS_DIR && mkdir  $_


3dcopy $phase phase.nii.gz -overwrite
3dcopy $mag   mag.nii.gz -overwrite
3dcopy "$epi" mc_target.nii.gz -overwrite
test -n "$mprage_bet" -a ! -r mprage_bet.nii.gz && ln -s "$mprage_bet" $_
# done by prepare_fieldmap (not preproc_fieldmap) 

if [ -z "$mprage_bet" ]; then
   echo "Run without warp to structural"
   test ! -r mc_target_brain_restore.nii.gz && 3dcopy mc_target.nii.gz $_
   3dcopy mc_target.nii.gz EF_D_mc_target.nii.gz -overwrite
   prepare_gre_fieldmap mag.nii.gz phase.nii.gz
   cd $savedir
   ! test -r FM_UD_fmap.nii.gz  && ln -s unwarp/$_ ./
   preproc_fieldmap
   echo "INSPECT OUTPUT: "
   echo "  afni" $savedir/EF_*D_mc_target.nii.gz
   echo " and/or "
   echo "  feh $savedir/qa/undistort_mc_target.png"
   exit 
fi


## deal with fieldmap files
# create FM* files: FM_UD_fmap FM_UD_fmap_mag
DISTORTION_DIR=$savedir/fm_unwarp
preprocessDistortion -phase $phase -mag $mag -fm_cfg $fm_cfg -savedir $DISTORTION_DIR -method gre.nii.gz
DISTORTION_DIR=$DISTORTION_DIR/unwarp

cd $savedir
! test -r  EF_D_mc_target.nii.gz && 3dcopy mc_target.nii.gz  $_

# create sigloss, mask, and warps
#[ ! -r EF_UD_mc_target.nii.gz ] && preproc_fieldmap
#preproc_fieldmap
func_struct_dof=$fmap_struct_dof
mprageBet="$mprage_bet"
prepare_mc_target
prepare_fieldmap 
cd $savedir # might not return to the correct directory
register_func2struct

# no bbr version
set -x
func_to_t1=""
test -r unwarp/T1_UD_warp.nii.gz && func_to_t1=$_ # TODO: untested. what is non-bbr output name?
test -r unwarp/T1_UD_warp_bbr.nii.gz && func_to_t1=$_
[ -z "$func_to_t1" ] && echo "ERROR: cannot find unwarp/T1_UD*" && exit 1
applywarp --in=mc_target.nii.gz --out=EF_UD_anat.nii.gz --interp=spline --ref=mprage_bet.nii.gz --warp=$func_to_t1
ln -s EF_UD_anat.nii.gz "$(basename "$(dirname "$savedir")")_func_in_anat.nii.gz"


