function Z = RtoZ(C,df)
%
% FUNCTION:     RtoZ -- Computes Fisher r-to-Z transform on correlation matrices.
%
% USAGE:        Z = RtoZ(C,df)
%
% Inputs:       C      -- Correlation matrix. Can be multi-dimensional
%               df     -- df matrix. Must have the same dimensions as C.
%                         This is a matrix of edge df values. Edge df
%                         values can be generated by the function MinPairEDOF.
%
% Outputs:      Z      -- Z transformed correlation values normalised for
%                         edge df.
%
% EXAMPLE:      Z = RtoZ(cmat, dfmat)
%
% AUTHOR:       Ameera X Patel
%
% CREATED IN:   MATLAB 7.13
%
% REVISION:     4 (19-11-17)
%
% COPYRIGHT:    Ameera X Patel (2017), University of Cambridge
%
% TOOLBOX:      BrainWavelet Toolbox v2.0

% ID: calccshift.m 4 19-11-2017 BWTv2.0 axpatel

%% Check files/inputs 

fname=mfilename;
if nargin<1
    help(fname); return;
end

if chkninput(nargin,[2,2],nargout,[0,1],fname)>=1
    Z=[]; return;
end

err=struct();
err(1).inp=chkintype(C,'double',fname);
err(2).inp=chkintype(df,'double',fname);

if sum(cat(1,err.inp))>=1;
    Z=[]; return;
end

%% Check matrix dimensions

Cdim=size(C);
Ndim=length(Cdim);

if ~isequal(size(df),Cdim)==1
    cprintf('_err','*** BrainWavelet Error ***\n')
    cprintf('err','Dimensions of correlation matrix and df matrix\n')
    cprintf('err','do not match.\n\n')
    Z=[]; return;
end

% switch Ndim
% case 2,
%     if ~isequal(Cdim(1),Cdim(2));
%         cprintf('_err','*** BrainWavelet Error ***\n')
%         cprintf('err','Input must be a correlation matrix.\n')
%         cprintf('err','No two dimensions of input match.\n\n')
%         Z=[]; return;
%     end
% case 3,
%     [minN,minInd]=min(size(C));
%     Dims=[1,2,3];
%     Dims(Dims==minInd)=[];
% 
%     if ~isequal(size(C,Dims(1)),size(C,Dims(2)));
%         cprintf('_err','*** BrainWavelet Error ***\n')
%         cprintf('err','Input must be a correlation matrix.\n')
%         cprintf('err','No two dimensions of input match.\n\n')
%         Z=[]; return;
%     end
% end

% if Ndim>=4
%     cprintf('_err','*** BrainWavelet Error ***\n')
%     cprintf('err','Too many dimensions in inputs.\n')
%     return;
% end

%% Set min df=3 and compute Z score from Fisher-Z transform

df(df<3)=3;
Z=0.5.*log((1+C)./(1-C)).*sqrt(df-3);

end
