#!/bin/bash

#function for taking sequential processing pictures (used in FM unwarping for now)
# Whether to take sequential pictures of processing steps
[ -z "$pics" ] && pics=no #=yes, take

globalcount=0 #order of processing
function _picture {
    # only do this if we are told to
    [ "$pics" == "yes" ] || return 0

    # check we have a save directory
    [ -d $imgdir ] || mkdir $imgdir 

    globalcount=$((( $globalcount+ 1))) #let ..++ can return 0 and break things with set -e 
    name=$(basename $(basename $1 .gz) .nii)
    num=$(printf "%04d" $globalcount)
    imgname=$imgdir/${num}_$name.png
    slicer -u $1 -a $imgname
    convert -scale 200% -fill white -gravity southwest -annotate 0 "$num $name:  $2" $imgname $imgname
}

function deleteFile() {
    #echo "to del: $1"

    #delete a file, if it exists
    if [ -f "$1" ]; then
	rel "rm -f \"$1\""
    fi
}

#rel is shorthand for "run, echo, log"
function rel() {
    #function that runs, echos to terminal, and logs to file an arbitrary command
    cmd="${1}"
    comment=0
    if [[ -n "${2}" && ${2} = c ]]; then
	comment=1
    fi
    
    if [ $comment -eq 0 ]; then
	#echo command to screen verbatim
	echo ${cmd}

	#run command
	eval ${cmd}
	cmdExit=$?
    else
	#echo command to screen with dashes to offset text visually
	echo -e "----  ${cmd}"
    fi
    
    if [ -n "${logFile}" ]; then
	if [ $comment -eq 1 ]; then
	    cmd="## ${cmd}"
	fi
	echo -e "${cmd}" >> "${logFile}"
    fi

    return $cmdExit
}

function dimon {
    [ $# -ne 2 ] && echo "dimon function requires <dicom pattern> <output prefix>" && exit 1

    dpat="$1"
    outbase="$2"
    
    #backup ${outbase}.nii if it exists so that Dimon doesn't bomb out
    [ -f "${outbase}.nii" ] && mv "${outbase}.nii" "${outbase}_bak.nii"
    [ -f "${outbase}.nii.gz" ] && mv "${outbase}.nii.gz" "${outbase}_bak.nii.gz"

    rel "Dimon \
	    -infile_pattern \"${dpat}\" \
	    -GERT_Reco \
	    -quit \
	    -dicom_org \
	    -gert_write_as_nifti \
	    -gert_create_dataset \
	    -gert_to3d_prefix \"${outbase}\""

    #-sort_by_acq_time

    rm -f dimon.files*
    rm -f GERT_Reco_dicom*

    #if afnirc has compressor on, then above will already generate nii.gz
    if [ -f "${outbase}.nii" ]; then
	rel "gzip -f \"${outbase}.nii\"" #use -f to force overwrite in case where functional.nii.gz exists, but we want to replace it.
    fi

}

function cleanup_preprocessMprage {
    imrm ${T1}_fast_totbias ${T1}_s20 ${T1}_initmask_s20 ${T1}_hpf ${T1}_hpf2_brain ${T1}_hpf2_s20 \
	${T1}_hpf_brain ${T1}_hpf_brain_mask ${T1}_hpf_s20 \
	${T1}_initfast2_bias ${T1}_initfast2_brain_mask ${T1}_initfast2_brain_mask2 \
	${T1}_initfast2_restore ${T1}_initfast2_seg ${T1}_initfast_bias \
	${T1}_initfast_restore ${T1}_initfast_seg ${T1}_fast_bias_vol2 \
	${T1}_fast_bias_vol32 template_to_subject_warpcoef ${T1}_fast_bias_idxmask
}


function cleanup_preprocessFunctional {

    if [ ${despike} -eq 1 ]; then
	dspre="d"
	deleteFile d_${funcNifti}
    else	   
	dspre=""
    fi

    if [ $no_warp -eq 0 ]; then
	wpre="w"
    else
	wpre=""
    fi

    if [ -n "${fm_phase}" ]; then
	upre="u"
    else
	upre=""
    fi

    #echo "dspre: $dspre"
    #echo "upre: $upre"
    #echo "smoothing_suffix: $smoothing_suffix"
    #echo "ext: $ext"

    #interleaved stream
    deleteFile t${dspre}_${funcFile}${ext}
    deleteFile mt${dspre}_${funcFile}${ext}
    deleteFile ${upre}mt${dspre}_${funcFile}${ext}
    deleteFile ${upre}mt${dspre}_${funcFile}_mean_reg${ext}
    deleteFile k${upre}mt${dspre}_${funcFile}${ext}
    deleteFile k${upre}mt${dspre}_tmean_mask${ext}
    deleteFile ${wpre}k${upre}mt${dspre}_${funcFile}${ext}
    deleteFile ${wpre}k${upre}mt${dspre}_${funcFile}_extents_mask${ext}
    deleteFile s${wpre}k${upre}mt${dspre}_${funcFile}${smoothing_suffix}${ext}
    deleteFile fs${wpre}k${upre}mt${dspre}_${funcFile}${smoothing_suffix}${ext}

    deleteFile k${upre}mt${dspre}_${funcFile}_Tmin${ext}
    deleteFile k${upre}mt${dspre}_${funcFile}_Tmin_10pctThr${ext}
    deleteFile ${upre}mt${dspre}_tmean${ext}
    deleteFile k${upre}mt${dspre}_tmean${ext}
    deleteFile ${wpre}k${upre}mt${dspre}_${funcFile}_tmean${ext}
    deleteFile fs${wpre}k${upre}mt${dspre}_mean_float${ext}
    deleteFile k${upre}mt${dspre}_${funcFile}_98_2_mask${ext}
    deleteFile k${upre}mt${dspre}_${funcFile}_98_2_mask_dil1x${ext}
    deleteFile k${upre}mt${dspre}_${funcFile}_masked${ext}
    deleteFile s${wpre}k${upre}mt${dspre}_${funcFile}${smoothing_suffix}_usan_size${ext}

    #with one-step warp, often get files such as wuktmd where FM unwarping and MNI warp are adjacent
    deleteFile mt${dspre}_${funcFile}${ext}
    deleteFile mt${dspre}_${funcFile}_mean_reg${ext}
    deleteFile kmt${dspre}_${funcFile}${ext}
    deleteFile kmt${dspre}_tmean_mask${ext}
    deleteFile ${wpre}${upre}kmt${dspre}_${funcFile}${ext}
    deleteFile ${wpre}${upre}kmt${dspre}_${funcFile}_extents_mask${ext}
    deleteFile s${wpre}${upre}kmt${dspre}_${funcFile}${smoothing_suffix}${ext}
    deleteFile fs${wpre}${upre}kmt${dspre}_${funcFile}${smoothing_suffix}${ext}

    deleteFile k$mt${dspre}_${funcFile}_Tmin${ext}
    deleteFile k$mt${dspre}_${funcFile}_Tmin_10pctThr${ext}
    deleteFile mt${dspre}_tmean${ext}
    deleteFile kmt${dspre}_tmean${ext}
    deleteFile ${wpre}${upre}kmt${dspre}_${funcFile}_tmean${ext}
    deleteFile fs${wpre}${upre}kmt${dspre}_mean_float${ext}
    deleteFile kmt${dspre}_${funcFile}_98_2_mask${ext}
    deleteFile kmt${dspre}_${funcFile}_98_2_mask_dil1x${ext}
    deleteFile kmt${dspre}_${funcFile}_masked${ext}
    deleteFile s${wpre}${upre}kmt${dspre}_${funcFile}${smoothing_suffix}_usan_size${ext}


    #sequential stream
    deleteFile m${dspre}_${funcFile}${ext}
    deleteFile m${dspre}_${funcFile}_mean_reg${ext}
    deleteFile ${upre}m${dspre}_${funcFile}${ext}
    deleteFile t${upre}m${dspre}_${funcFile}${ext}
    deleteFile kt${upre}m${dspre}_${funcFile}${ext}
    deleteFile kt${upre}m${dspre}_tmean_mask${ext}
    deleteFile ${wpre}kt${upre}m${dspre}_${funcFile}${ext}
    deleteFile ${wpre}kt${upre}m${dspre}_${funcFile}_extents_mask${ext}
    deleteFile s${wpre}kt${upre}m${dspre}_${funcFile}${smoothing_suffix}${ext}
    deleteFile fs${wpre}kt${upre}m${dspre}_${funcFile}${smoothing_suffix}${ext}

    deleteFile kt${upre}m${dspre}_${funcFile}_Tmin${ext}
    deleteFile kt${upre}m${dspre}_${funcFile}_Tmin_10pctThr${ext}
    deleteFile t${upre}m${dspre}_tmean${ext}
    deleteFile kt${upre}m${dspre}_tmean${ext}
    deleteFile ${wpre}kt${upre}m${dspre}_${funcFile}_tmean${ext}
    deleteFile fs${wpre}kt${upre}m${dspre}_mean_float${ext}
    deleteFile kt${upre}m${dspre}_${funcFile}_98_2_mask${ext}
    deleteFile kt${upre}m${dspre}_${funcFile}_98_2_mask_dil1x${ext}
    deleteFile kt${upre}m${dspre}_${funcFile}_mask${ext}
    deleteFile kt${upre}m${dspre}_${funcFile}_masked${ext}
    deleteFile s${wpre}kt${upre}m${dspre}_${funcFile}${smoothing_suffix}_usan_size${ext}

    #with one-step warp, often get files such as wuktmd where FM unwarping and MNI warp are adjacent
    deleteFile m${dspre}_${funcFile}${ext}
    deleteFile tm${dspre}_${funcFile}${ext}
    deleteFile ktm${dspre}_${funcFile}${ext}
    deleteFile ktm${dspre}_tmean_mask${ext}
    deleteFile ${wpre}${upre}ktm${dspre}_${funcFile}${ext}
    deleteFile ${wpre}${upre}ktm${dspre}_${funcFile}_extents_mask${ext}
    deleteFile s${wpre}${upre}ktm${dspre}_${funcFile}${smoothing_suffix}${ext}
    deleteFile fs${wpre}${upre}ktm${dspre}_${funcFile}${smoothing_suffix}${ext}

    deleteFile ktm${dspre}_${funcFile}_Tmin${ext}
    deleteFile ktm${dspre}_${funcFile}_Tmin_10pctThr${ext}
    deleteFile tm${dspre}_tmean${ext}
    deleteFile ktm${dspre}_tmean${ext}
    deleteFile ${wpre}${upre}ktm${dspre}_${funcFile}_tmean${ext}
    deleteFile fs${wpre}${upre}ktm${dspre}_mean_float${ext}
    deleteFile ktm${dspre}_${funcFile}_98_2_mask${ext}
    deleteFile ktm${dspre}_${funcFile}_98_2_mask_dil1x${ext}
    deleteFile ktm${dspre}_${funcFile}_mask${ext}
    deleteFile ktm${dspre}_${funcFile}_masked${ext}
    deleteFile s${wpre}${upre}ktm${dspre}_${funcFile}${smoothing_suffix}_usan_size${ext}

    deleteFile ${preSmooth}_mask_allbrain${ext}
    deleteFile ${preSmooth}_mask_edgecorrection${ext}

    #general files
    deleteFile mc_mean_vol_target${ext}
    deleteFile premc_mean_vol${ext}

    deleteFile func_to_struct.mat
    deleteFile func_to_struct_init.mat #6 dof transform prior to BBR
    deleteFile fmap2epi_bbr.mat
    deleteFile struct_to_func.mat
    deleteFile func_to_struct${ext}
    deleteFile func_to_struct_allv${ext}
    deleteFile func_to_struct_nounwarp${ext}

    deleteFile mask_${funcFile}_Tmin_10pctThr${ext}

    deleteFile ${prefix}tmean${smoothing_suffix}${ext}

    #some more here...
    deleteFile "${threshMask}_2struct${ext}"
    deleteFile *98_2_mask_dil1x_outOfAnatBounds${ext}
    deleteFile templateMask${ext}

    [[ $constrainToTemplate = [Nn] ]] && deleteFile *98_2_mask_dil1x_templateTrim${ext}

    deleteFile func_to_standard_warp_allv${ext} #onestep_warp when warp is not volume-wise

    rm -rf mcOrig
    rm -rf unwarptemps #intermediate fieldmap files
    [ -d mc_mats ] && rm -rf mc_mats #original motion transformation matrices

    deleteFile example_func${ext}
    deleteFile premc_mean_vol${ext}
    deleteFile mc_initial${ext} #initial motion correction to mean functional
    deleteFile mc_target_mask${ext} #brain mask for mc_target used for rmsdiff in motion_plots

    deleteFile "*${funcFile}*_rel_mean.rms" #shouldn't be necessary anymore since we compute rms ourselves
    deleteFile "*${funcFile}*_abs_mean.rms"
    deleteFile "_${funcNifti}" #initial reoriented file with just a prepended underscore

    #file containing individual volumes of 4d dataset after fslsplit (used for MC+unwarping)
    [ -d episplit ] && rm -rf episplit

}
