#!/bin/bash
function highpass_filter {

    [ $no_hp -eq 1 ] && return 0 #skip high-pass filtering

    if [[ ! -f ".temporal_filtering_complete" ]]; then
	
	rel "High-pass filtering functional data to remove signals slower than $hpFilter volumes" c

	#Beginning with FSL 5.0.7, bptf removes the mean component. Thus, need to add this back after filtering.
	read fslversion < $FSLDIR/etc/fslversion
	fslversion=${fslversion//./} #remove all periods
	if [ $fslversion -ge 507 ]; then
	    rel "fslmaths \"${prefix}${funcFile}${smoothing_suffix}\" -Tmean tempMean"
	    rel "fslmaths \"${prefix}${funcFile}${smoothing_suffix}\" -bptf $hpFilter -1 -add tempMean \"f${prefix}${funcFile}${smoothing_suffix}\""
	    rel "imrm tempMean"
	else
	    rel "fslmaths \"${prefix}${funcFile}${smoothing_suffix}\" -bptf $hpFilter -1 \"f${prefix}${funcFile}${smoothing_suffix}\""
	fi

	rel "date > .temporal_filtering_complete"

    fi
    prefix="f${prefix}"

}
