#!/bin/bash

function parse_args {
    ## parse input arguments, initialize default parameter settings
    ## when called from preprocessFunctional, must pass "$@", which is all input parameters to script
    
    #initialize defaults
    funcFile=
    arma_nuisance_regression=1 #use 3dREMLfit by default when fitting nuisance regression (see Bright & Murphy 2017)
    bandpass_filter=0 #no bandpass by default
    local bids_sidecar="" # json sidecar with slicetiming information
    betFrac=0.3 #default fractional intensity threshold
    cleanup=0
    cleanup_only=0
    compute_warp=0 #used for -compute_warp_only. Specifies to compute warp to template without applying it to preprocessed data.
    constrainToTemplate="y"
    deoblique_all=0
    despike=0
    despikeThresh="2.5 4.0"
    delDicom=
    detectSiemens=0
    dicomPattern=
    DISTORTION_DIR= # alterntaive to preprocessing fieldmaps within preprocessFunctional (more like preprocessMprage). dir most likely named "warp"
    dte=
    dwelltime=     #effective echo spacing. set by -epi_echospacing or by fmcfg file or read from sepos .json (BIDS)
    epiTE= # seconds, in -fmcfg or read from BIDS
    flip_topup_pedir=0
    fmap_struct_dof="bbr"
    fm_phase=
    fm_magnitude=
    fm_cfg=
    funcRefimg=
    func_struct_dof="bbr" #boundary-based registration in FSL 5.0+
    funcWarpInterp="spline"
    # N.B. funcdir=$(pwd) in preprocessFunctional
    gsr_in_prefix=0
    hpFilter=120s #default to 120s hp filter
    ica_aroma=0 #whether to run smoothed data through ICA-AROMA
    local ignore_bids=0 # should we look a the bids sidecar?
    logFile="preprocessFunctional.log"
    MATLAB_RAM_limit=3 #3GB wavelet despike RAM limit by default (more is faster, but can be a hog when processing in parallel).
    MATLAB_single_thread=    
    mc_first= #default to empty and choose at stage of motion + slice timing depending on user specification and slice acquisition order
    mc_movie=0
    mc_program="mcflirt"
    motionCensor=
    motionSinc="y"
    no_hp=0
    no_st=0
    no_mc=0
    no_smooth=0
    no_warp=0
    nuisance_regression=0
    nuisance_compute=0
    nuisance_file=.nuisance_regressors
    [ -z "$MATLAB_RAM_limit" ] && MATLAB_RAM_limit=3 #3GB wavelet despike RAM limit by default (more is faster, but can be a hog when processing in parallel).
    [ -z "$MATLAB_single_thread" ] && MATLAB_single_thread=
    output_basename=functional #base prefix of NIfTI file after dicom -> NIfTI conversion
    partial_proc=""
    use_physio=""
    physio_resp="" # respitory file (1D or .resp [siemens])
    physio_card="" #pulse file (1D or .puls [siemens])
    physio_func_info="" # dicom directory/json file, used for timing info to extract resp+puls files
    prefer_ants=1 #use 6dof ANTS registration over flirt, when possible
    ref_vol=  #don't set a motion correction reference volume by default
    rescalingMethod="10000_globalmedian" #scale whole brain 4D by single constant to normalize median to 10000.
    rmautocorr=0 # -rmautocorr, return the -Rwherr -- ARMA(1,1) prewhitened residuals -- from 3dREMLfit when computing nuisance regression. DEFAULT is return unwhitened residuals
    rmgroup_component_1d=""
    se_phasepos=
    se_phaseneg=
    signallossthresh=0.9 # Areas with 90% or more signal loss in fieldmap are masked out. Will be overridden by an fmcfg file if specified
    sliceAcquisition= #never assume slice acquistion order. Force definition or use auto-detect from DICOM.
    sliceMotion4D=0
    sliceTimesFile=
    smoother="susan"
    smoothing_kernel="5"
    st_first= #default to empty and choose default based on slice acquisition order (sequential versus interleaved)
    thresholdMethod="98_2"
    tr= #never assume a TR. Force definition or use auto-detect from DICOM.
    templateBrain="${stddir}/mni_icbm152_nlin_asym_09c/mni_icbm152_t1_tal_nlin_asym_09c_brain_3mm" #default to new 2009 MNI
    templateName=MNI_3mm
    unwarpdir= #set by -epi_pedir or by fmcfg file
    waveletDespike=0
    waveletM1000=0
    waveletThreshold=10
    verbose=
    KEEP_MOTION_FILES=
    n_rm_firstvols=0
    USE_OLD_TEMPLATE=
    unifize_funcref=0

    #figure out file extension for FSL programs
    if [ -z $FSLOUTPUTTYPE ]; then
	export FSLOUTPUTTYPE=NIFTI_GZ
    fi

    if [ $FSLOUTPUTTYPE = NIFTI_GZ ]; then
	ext=".nii.gz"
    elif [ $FSLOUTPUTTYPE = NIFTI ]; then
	ext=".nii"
    else
	echo "Not setup to handle FSLOUTPUTTYPE: $FSLOUTPUTTYPE."
	exit 1
    fi

    #if no parameters are passed in, then print help and exit.
    if [ $# -eq 0 ]; then
	#check for resume
	if [ -f .preproc_cmd ]; then
	    read cmd < .preproc_cmd
	    #delete -startover from positional parameters, if present
	    #if running -cleanup_only, don't want to delete .*complete files.
	    #if running -startover, don't need to run rm_completefiles again.
	    cmd="${cmd/-startover/}"
	    echo -e "\npreprocessFunctional called initially with parameters below:\n\n"
	    echo "$cmd"
	    local resume=
	    until [[ "$resume" = [ny] ]]; do
		echo ""
		read -sn1 -p "Resume run with these settings? (y/n)" resume
	    done
	    echo ""

	    if [ $resume = y ]; then
              #disable wildcard expansion so that -dicom patterns don't get expanded
		set -f 
              # change positional parameters to stored settings
		set -- $cmd
              # re-enable wildcard expansion as usual
		set +f
	    else
		echo -e "\n\nQuitting script."
		exit 0
	    fi
	else
	    printHelp
	    exit 0
	fi
    elif [ $# -eq 1 ]; then
       if [ $1 = -check_dependencies ]; then 
          set +e
          trap - ERR
          if ! (command -v matlab >/dev/null || command -v octave >/dev/null); then
             echo "Optional: matlab or octave is required for wavelet despiking" >&2
          fi
          check_dep_list 3dcalc fslmaths python antsRegistrationSyN.sh c3d_affine_tool \
             python:nipy python:nibabel python:future R:oro.nifti R:orthopolynom python:seaborn \
             python:ica_aroma \
             perl:App::AFNI::SiemensPhysio \

          exit $?
	elif [ $1 = -cleanup_only ]; then
	    cleanup_only=1
	    cleanup=1
	elif [ $1 = -startover ]; then
	    rm_completefiles
	elif [ $1 = -help ]; then
	    printHelp
	    exit 0
	elif [ $1 = -cite ]; then
           cat $(dirname $0)/citations.txt
	    exit 0
	elif [ $1 = -resume ]; then
	    echo "Resuming preprocessing using existing settings."
	else
	    echo "Unable to determine what to do with call: preprocessFunctional ${1}"
	    exit 1
	fi

	if [ -f .preproc_cmd ]; then
	    read cmd < .preproc_cmd
	    cmd="${cmd/-startover/}"
           # disable wildcard expansion so that -dicom patterns don't get expanded
           set -f 
           # change positional parameters to stored settings
	    set -- $cmd
           # re-enable wildcard expansion as usual
	    set +f 
	else
	    echo "-cleanup_only or -startover specified alone, but no known preprocessing call in .preproc_cmd."
	    exit 1
	fi

    elif [ $# -eq 2 ] && 
         [[ "$@" =~ -cleanup ]] && # cleanup or cleanup_only, doesn't matter
         [[ "$@" =~ -keep_motion_files ]]; then
	cleanup_only=1
	cleanup=1
       KEEP_MOTION_FILES=1
	if [ -f .preproc_cmd ]; then
	    read cmd < .preproc_cmd
	    cmd="${cmd/-startover/}"
           # disable wildcard expansion so that -dicom patterns don't get expanded
           set -f 
           # change positional parameters to stored settings
	    set -- $cmd
           # re-enable wildcard expansion as usual
	    set +f 
	else
	    echo "doesn't look like we've run anything yet. dont know how to -cleanup_only and -keep_motion_files"
	    exit 1
	fi
      
    else
       # don't overwrite
       [ -r .preproc_cmd ] && mv .preproc_cmd .preproc_cmd_mv$(date +%s)
	#write the parameter settings to file
       # for resuming failed run.
	echo "$@" > .preproc_cmd 
    fi

    #echo "about to process with cmd: $@"

    #process command line parameters
    while [ _$1 != _ ] ; do
	if [[ $1 = -4d || $1 = -4D ]] ; then
	    funcFile="${2}"
	    funcNifti="${funcFile}" #retains file extension
	    shift 2
	elif [ $1 = -4d_slice_motion ]; then
	    sliceMotion4D=1
	    mc_program="sliceMotion4d"
	    shift 1
	elif [ $1 = -bids_sidecar ]; then
          bids_sidecar="$2";
          [ ! -r "$bids_sidecar" ] && echo "ERROR: no sidecar '$bids_sidecar'" && exit 1
          shift 2
	elif [ $1 = -bandpass_filter ]; then
	    no_hp=1 #bandpass and high-pass are mutually exclusive
	    bandpass_filter=1
	    bpLow="${2}"
	    bpHigh="${3}"
	    shift 3
	elif [ $1 = -bet_frac ]; then
	    betFrac="${2}"
	    shift 2
	elif [ $1 = -cleanup ]; then
	    cleanup=1
	    shift 1
	elif [ $1 = -cleanup_only ]; then
	    #I'm a bit dubious about letting -cleanup_only be passed alongside the rest of a call, rather than
	    #relying on the .preproc_cmd code above, but keeping this for now.
	    cleanup_only=1
	    cleanup=1
	    shift 1
	elif [ $1 = -compute_warp_only ]; then
	    no_warp=1
	    compute_warp=1
	    shift 1
	elif [ $1 = -custom_slice_times ]; then
	    sliceTimesFile="$2"
	    sliceMotion4D=1 #for now, this option is only relevant for sliceMotion4d correction
	    shift 2
	elif [ $1 = -constrain_to_template ]; then
	    if [[ $2 = [NnYy] ]]; then
		constrainToTemplate="${2}"
		shift 2
	    else
		echo -e "Unrecognized -constrain_to_template parameter: ${2}.\n  Options are: y or n."
		exit 1
	    fi
	elif [ $1 = -delete_dicom ]; then
	    if [[ $2 = "delete" || $2 = "yes" || $2 = "no" || $2 = "archive" ]]; then
		delDicom="${2}"
		shift 2
	    else
		echo -e "Unrecognized -delete_dicom: ${2}.\n  Options are: -delete_dicom delete yes no archive."
		exit 1
	    fi
	elif [ $1 = -deoblique_all ]; then
	    deoblique_all=1
	    shift 1
	elif [ $1 = -despike ]; then
	    despike=1
	    shift 1
	elif [ $1 = -despike_thresh ]; then
	    despike=1
	    despikeThresh="$2 $3"
	    shift 3
	elif [ $1 = -dicom ]; then
	    dicomPattern="${2}"
	    shift 2
	elif [ $1 = -distortion_dir ]; then
	    DISTORTION_DIR=$(abspath "${2}")
           [ -z "$DISTORTION_DIR" -o ! -d "$DISTORTION_DIR" ] && echo "distortion_dir '$2' ('$DISTORTION_DIR') DNE!" && exit 1
           # use fm_cfg from distortion directory unless we've already specifed a fm_cfg
           test -z "$fm_cfg" -a -r "$DISTORTION_DIR/fm.cfg"  && export fm_cfg="$_"
	    shift 2
	elif [ $1 = -epi_echospacing ]; then
	    dwelltime="${2}"
	    shift 2
	elif [ $1 = -epi_pedir ]; then
	    unwarpdir="${2}" #should be x/x-/y/y-/z/z-

	    #fix pickiness of FUGUE
	    [ "$unwarpdir" = -x ] && unwarpdir="x-" && echo "Please use -epi_pedir x-"
	    [ "$unwarpdir" = -y ] && unwarpdir="y-" && echo "Please use -epi_pedir y-"
	    [ "$unwarpdir" = -z ] && unwarpdir="z-" && echo "Please use -epi_pedir z-"
	    shift 2
	elif [ $1 = -epi_te ]; then #echo time of EPI data
	    epiTE=$( echo "($2)/1000" | bc -l ) # convert TE into seconds for sigloss
	    shift 2
	elif [ $1 = -flip_topup_pedir ]; then
	    flip_topup_pedir=1
	    shift 1
	elif [ $1 = -fmap_struct_dof ]; then
	    if [[ $2 = "bbr" || $2 = "6" || $2 = "7" || $2 = "12" ]]; then
		fmap_struct_dof="${2}"
		shift 2
	    else
		echo -e "Unrecognized -fmap_struct_dof: ${2}.\n  Options are: -fmap_struct_dof bbr, 6, 7, 12."
		exit 1
	    fi
	elif [ $1 = -fm_phase ]; then
	    fm_phase="${2}"
	    shift 2
	elif [ $1 = -fm_magnitude ]; then
	    fm_magnitude="${2}"
	    shift 2
	elif [ $1 = -fm_cfg ]; then
	    fm_cfg="${2}"
	    shift 2
	elif [[ $1 = -func_struc_dof || $1 = -func_struct_dof ]]; then
	    if [[ $2 = "bbr" || $2 = "6" || $2 = "7" || $2 = "12" ]]; then
		func_struct_dof="${2}"
		shift 2
	    else
		echo -e "Unrecognized -func_struct_dof: ${2}.\n  Options are: -func_struct_dof bbr, 6, 7, 12."
		exit 1
	    fi
	elif [ $1 = -func_refimg ]; then
	    funcRefimg="${2}"
	    shift 2
	elif [ $1 = -help ]; then	
	    printHelp
	    exit 0
	elif [ $1 = -hp_filter ]; then
	    hpFilter="${2}"
	    shift 2
	elif [ $1 = -gsr ]; then
	    gsr_in_prefix=1
	    shift 1
	elif [ $1 = -ica_aroma ]; then
	    ica_aroma=1
	    shift 1
	elif [ "$1" = -ignore_bids ]; then
	    ignore_bids=1
	    shift 1
	elif [ $1 = -log ]; then
	    logFile="${2}"
	    shift 2
	elif [ $1 = -mc_first ]; then
	    mc_first=1
	    st_first=0
	    shift 1
	elif [ $1 = -mc_movie ]; then
	    mc_movie=1
	    shift 1
	elif [ $1 = -mc_program ]; then
	    if [[ $2 = "3dvolreg" || $2 = "mcflirt" ]]; then
		mc_program="${2}"
		shift 2
	    else
		echo -e "Unrecognized -mc_program: ${2}.\n  Options are: -mc_program 3dvolreg, mcflirt."
		exit 1
	    fi
	elif [ $1 = -motion_censor ]; then
	    motionCensor="${2}"
	    shift 2
	elif [ $1 = -motion_sinc ]; then
	    if [[ $2 = [NnYy] ]]; then
		motionSinc="${2}"
		shift 2
	    else
		echo -e "Unrecognized -motion_sinc parameter: ${2}.\n  Options are: y or n."
		exit 1
	    fi
	elif [ $1 = -mprage_bet ]; then
	    mprageBet="${2}"
	    shift 2
	elif [ $1 = -no_mc ]; then
	    no_mc=1
	    shift 1
	elif [ $1 = -no_hp ]; then
	    no_hp=1
	    shift 1
	elif [ $1 = -no_smooth ]; then
	    no_smooth=1
	    shift 1
	elif [ $1 = -no_st ]; then
	    no_st=1
	    shift 1
	elif [ $1 = -no_warp ]; then
	    no_warp=1
	    shift 1
	elif [ $1 = -nuisance_file ]; then
	    nuisance_file="${2}"
	    shift 2
	elif [ $1 = -nuisance_compute ]; then
	    nuisance_compute=1
	    nuisance_regressors="${2}"
	    shift 2
	elif [ $1 = -nuisance_regression ]; then
	    nuisance_regression=1
	    nuisance_regressors="${2}"
	    shift 2
	elif [ $1 = -ols_nuisance_regression ]; then
	    arma_nuisance_regression=0
	    shift 1
	elif [ $1 = -output_basename ]; then
	    output_basename="${2}"
	    shift 2
	elif [ $1 = -partial_proc ]; then
           # 20190729 only supporting stopping after motion and warp 
           partial_proc="${2}"
           local partial_proc_opts="motion|despike|warp|smooth"
           ! [[ $partial_proc =~ $partial_proc_opts ]] && 
              echo "-partial_proc only supports ${partial_proc_opts//\|/ }" &&
              return 1
	    shift 2
	elif [ $1 = -physio_resp ]; then
           physio_resp="$(abspath "${2}")"
           use_physio=1
	    shift 2
	elif [ $1 = -physio_card ]; then
           physio_card="$(abspath "${2}")"
           use_physio=1
	    shift 2
	elif [ $1 = -physio_func_info ]; then
	    physio_func_info="${2}"
           [ -r "$physio_func_info" ] && physio_func_info="$(abspath "$physio_func_info")"
           use_physio=1
	    shift 2
	elif [ $1 = -prefer_ants ]; then
	    prefer_ants=1 #whether to use ANTS for 6dof rigid coregistration when possible
	    shift 1
	elif [ $1 = -prefer_flirt ]; then
	    prefer_ants=0
	    shift 1
	elif [ $1 = -ref_vol ] ; then
            ref_vol="${2}"
            shift 2
	elif [ $1 = -rescaling_method ]; then
	    if [[ $2 = "10000_globalmedian" || $2 = "100_voxelmean" ]]; then
		rescalingMethod="${2}"
		shift 2
	    else
		echo -e "Unrecognized -rescaling_method: ${2}.\n  Options are: -rescaling_method 10000_globalmedian or -rescaling_method 100_voxelmean"
		exit 1
	    fi
	elif [ $1 = -rmautocorr ]; then
	    rmautocorr=1
	    shift 1
       # two pass preprocessing -- second pass removing group component
       elif [ $1 = -rmgroup_component ]; then
           rmgroup_component_1d="$2"
           shift 2
	elif [ $1 = -slice_acquisition ]; then
	    if [[ $2 = "interleaved" || $2 = "seqasc" || $2 = "seqdesc" ]]; then
		sliceAcquisition="${2}"
		shift 2
	    else
		echo "Slice acquisition setting not recognized. Options are: seqdesc, seqasc, and interleaved"
		exit 1
	    fi
	elif [ $1 = -se_phaseneg ]; then
	    se_phaseneg="${2}"
	    shift 2
	elif [ $1 = -se_phasepos ]; then
	    se_phasepos="${2}"
	    shift 2
	elif [ $1 = -siemens ]; then
	    detectSiemens=1
	    shift 1
	elif [ $1 = -smoother ]; then
	    smoother="${2}"
	    shift 2
	elif [ $1 = -startover ]; then
	    rm_completefiles
	    shift 1
	elif [ $1 = -smoothing_kernel ] ; then
            smoothing_kernel="${2}"
            shift 2
	elif [ $1 = -st_first ]; then
	    st_first=1
	    mc_first=0
	    shift 1
	elif [ $1 = -template_brain ]; then
	    templateName="${2}"
	    case $2 in
		Tal_3mm) templateBrain="${stddir}/talairach_fsl_mni152/TalFSL_MNI152_T1_3mm_brain" ;;
		MNI_FSL_3mm) templateBrain="${stddir}/fsl_mni152/MNI152_T1_3mm_brain" ;;
		MNI_FSL_2.3mm) templateBrain="${stddir}/fsl_mni152/MNI152_T1_2.3mm_brain" ;;
		MNI_FSL_2mm) templateBrain="${stddir}/fsl_mni152/MNI152_T1_2mm_brain" ;;		
		MNI_3mm) templateBrain="${stddir}/mni_icbm152_nlin_asym_09c/mni_icbm152_t1_tal_nlin_asym_09c_brain_3mm" ;;
		MNI_2.3mm) templateBrain="${stddir}/mni_icbm152_nlin_asym_09c/mni_icbm152_t1_tal_nlin_asym_09c_brain_2.3mm" ;;
		SPM_2mm) templateBrain="${stddir}/spm8_mni/T1_brain" ;;
		MNI_2mm) templateBrain="${stddir}/mni_icbm152_nlin_asym_09c/mni_icbm152_t1_tal_nlin_asym_09c_brain_2mm" ;;
		MNI_2mm) templateBrain="${stddir}/mni_icbm152_nlin_asym_09c/mni_icbm152_t1_tal_nlin_asym_09c_brain_2mm" ;;

              # 20210426. added to preprocessMprage ealier
              1YO_2mm)  templateBrain="${stddir}/UNCInfant/2mm/infant-1yr-brain";;
              1YO_3mm)  templateBrain="${stddir}/UNCInfant/2mm/infant-1yr-brain-3mm";;
              neo_2mm)  templateBrain="${stddir}/UNCInfant/2mm_neo/infant-neo-brain";;
              neo_3mm)  templateBrain="${stddir}/UNCInfant/2mm_neo/infant-neo-brain-3mm";;
		*) echo -e "Reference brain -template_brain ${2} not recognized. Options are MNI_3mm, MNI_FSL_3mm, SPM_2mm, Tal_3mm, 1YO_3mm, neo_3mm."; exit 1 ;;
	    esac
	    shift 2
	elif [ $1 = -threshold ]; then
	    if [[ $2 = "98_2" || $2 = "10" ]]; then
		thresholdMethod="${2}"
		shift 2
	    else
		echo -e "Unrecognized thresholding parameter: ${2}.\n  Options are: 98_2 or 10."
		exit 1
	    fi
	elif [ $1 = -tr ]; then
	    tr="${2}"
            shift 2
	elif [ $1 = -trio_tim ]; then
	    #deprecated: -siemens preferred
	    detectSiemens=1
	    shift 1
       elif [ $1 = -trunc ]; then
           n_rm_firstvols=$2
           shift 2

       # LNCD mMR/PET uses old template 
       elif [[ $1 = -use_old_mni  ]]; then
          USE_OLD_TEMPLATE=yes
          shift 1
       elif [[ $1 = -unifize_funcref ]]; then # added 20210513
	   unifize_funcref=1
          shift 1
	elif [ $1 = -verbose ]; then
	    verbose=1
	    set -xv
	    shift 1
	elif [ $1 = -warpcoef ]; then
	    warpCoef="${2}"
	    shift 2
	elif [ $1 = -warp_interpolation ]; then
	    if [[ $2 = "sinc" || $2 = "trilinear" || $2 = "spline" ]]; then
		funcWarpInterp="${2}"
		shift 2
	    else
		echo -e "Unrecognized -warp_interpolation parameter: ${2}.\n  Options are: sinc, spline, or trilinear."
		exit 1
	    fi
	elif [ $1 = -wavelet_despike ]; then
	    waveletDespike=1
	    despike=1
	    shift 1
	elif [ $1 = -wavelet_m1000 ]; then
	    waveletM1000=1
	    shift 1
	elif [ $1 = -wavelet_threshold ]; then
	    waveletThreshold="${2}"
	    shift 2
	elif [ $1 = -keep_motion_files ]; then
	    # probably dont see this, -cleanup_only skips this parsing
	    KEEP_MOTION_FILES=1
	    shift 1
	else
	    #printHelp
	    echo -e "----------------\n\n"
	    echo "Unrecognized command line parameter: ${1}"
	    exit 1
	fi
    done

    #If we have previously converted to NIfTI (dicom_to_nifti function), then the name of the file (i.e., funcNifti) should be stored in .functional. If this exists, read it and use it.
    if [ -f .functional ]; then
	[ -n "$funcFile" ] && local fcache="$funcFile"
	read funcNifti < .functional
	funcFile=$( remove_ext "$funcNifti" )

	if [[ -n "$fcache" && "$fcache" != "$funcFile" ]]; then
	    rel "This is odd. You seem to have specified -4d, but I found a .functional file, which implies starting from DICOM. I will use $funcFile, not $fcache" c
	fi
	
	if [ ! -r "$funcNifti" ]; then
	    rel "Tried to use the 4d file $funcNifti as input, but failed to locate it." c
	    exit 1
	fi
    fi

    #trim off file extension for functional file
    if [ -n "$funcFile" ]; then
	if [ ! -r ${funcFile} ]; then
	    #passed in parameter does not exist or does not have .nii or nii.gz extension. Need to test for file with added extension
	    if [ -r "${funcFile}.nii" ]; then
		funcNifti="${funcFile}.nii"
		rel "Assuming that ${funcNifti} is the intended -4d input." c
	    elif [ -r "${funcFile}.nii.gz" ]; then
		funcNifti="${funcFile}.nii.gz"
		rel "Assuming that ${funcNifti} is the intended -4d input." c
	    else
		rel "Raw functional 4d file: $funcFile does not exist.\nAttempted to look for ${funcFile}.nii and ${funcFile}.nii.gz to no avail.\nExiting.\n" c
		exit 1
	    fi
	fi

	if [ "${funcFile:(-7)}" = ".nii.gz" ]; then
	    #strip off the suffix for FSL processing and makes filenames easier to build.
	    lenFile=${#funcFile}
	    lenSub=$( expr $lenFile - 7 )
	    funcFile=${funcFile:0:$lenSub}
	elif [ "${funcFile:(-4)}" = ".nii" ]; then
	    #strip off the suffix for FSL processing
	    lenFile=${#funcFile}
	    lenSub=$( expr $lenFile - 4 )
	    funcFile=${funcFile:0:$lenSub}
	fi

       # tr and slicetiming defined by sidecar if it exists
       # and we want to use it (default)
       if [ "$ignore_bids" -eq 0 ]; then
          [ -z "$bids_sidecar" ] &&
            load_func_bids "$funcFile.json" ||
            load_func_bids "$bids_sidecar"
       fi
    fi

    #Not legal to pass in requests for MC versus ST order when using 4d slice + motion.
    if [[ $sliceMotion4D -eq 1 && $no_st -eq 1 ]]; then
	echo "Cannot request -no_st with -4d_slice_motion"
	exit 1
    fi

    if [[ $sliceMotion4D -eq 1 && $st_first -eq 1 ]]; then
	echo "Cannot request -st_first with -4d_slice_motion"
	exit 1
    fi

    if [[ $sliceMotion4D -eq 1 && $mc_first -eq 1 ]]; then
	echo "Cannot request -mc_first with -4d_slice_motion"
	exit 1
    fi

    # Not legal to use -gsr without also having it in regression
    if [[ $gsr_in_prefix -eq 1 && ! $nuisance_regressors =~ (^|,| )gs( |,|$) ]]; then
       echo "Cannot request -gsr without having gs in -nuisance_regressors ($nuisance_regressors)"
       exit 1
    fi

    # not legal to use motion regression and no_mc
    if [[ "$nuisance_regressors" =~ (dq)?(6m|((r|t)[xyz])) && $no_mc -eq 1 && ! -r motion.par ]]; then
       echo "Cannot request -nuisance_regression w/motion '$nuisance_regression' and -no_mc (unless motion.par exists)"
       exit 1
    fi

    # Not legal to use -rm_completefiles without warping
    if [[ -n "$rmgroup_component_1d" && $no_warp -ge 1 ]]; then
       echo "Cannot request -rmgroup_component and not preform a warp!"
       exit 1
    fi

    # Not legal to give just pulse or card
    #  as well as way to get func slice info 
    if [ -n "$use_physio" ]; then 
       if [ -z "$(which siemphysdat 2>/dev/null)" ];then
          echo "siemphysdat is not in your path! must install for physio preprocessing"
          echo "   see https://github.com/LabNeuroCogDevel/siemphysdat"
          exit 1
       fi
       # have all we need
       if [ -z "$physio_card" -o -z "$physio_resp" ]; then
          echo "-physio_resp and -physio_card must both be specified if any -physio_* option is used!"
          exit 1
       fi
       if [ -z "$physio_func_info" -o ! -r "$physio_func_info" ]; then
          echo "-physio_func_info must point to a dcm directory, dicom file, BIDS json file, or give a date string"
          exit 1
       fi
       # is a json file, will be passed to siemphysdat with -j
       if [ ! -d "$physio_func_info" ]; then
          physio_func_info="-j $physio_func_info" 
       fi
    fi

    #whether to use a fieldmap, either GRE or TOPUP
    use_fm=0
    if [[ -n "$fm_phase" || -n "$se_phasepos"  || -n "$DISTORTION_DIR" ]]; then
	use_fm=1
    fi

    #if using TOPUP (SE fieldmap approach), do we use the 'direct' pipeline (i.e., WarpField from TopupPreprocessingAll),
    #or the indirect approach of the rad/s field pushed through the typical GRE fieldmap pipeline (incl. registration to structural)
    [[ -n "$se_phasepos" ]] && topup_direct=1 || topup_direct=0 #hidden at the moment, perhaps expose option later
    
    #determine whether flirt version is new enough to handle BBR coregistration
    #if we have v6.0+, then incorporate fieldmap unwarping into BBR func2struct
    #and use resulting unwarping information for EPI -> unwarp -> struct -> MNI transform.
    #for older versions, need to use EPI-registered fieldmap for unwarping
    flirtVersion=$( flirt | head -1 | perl -pe 's/^FLIRT version ([0-9\\.]+)$/\1/' )
    bbrCapable=$( echo "${flirtVersion} >= 6" | bc )

    #The smoothing kernel parameter is expected to be the full width at half
    #maximum (FWHM) value (in mm). FWHM refers to the width of the Gaussian shape
    #on the x-axis at half of the maximum y value
    #(see http://imaging.mrc-cbu.cam.ac.uk/imaging/PrinciplesSmoothing).
    #It is common to conceptualize Gaussian curves in terms of their standard
    #deviation (sigma). Sigma is related to FWHM by the following equation:
    #FHWM=sigma * sqrt(8*log(2))
    #Hence, because FSL expects our smoothing specification to be a sigma,
    #we divide the FWHM value provided by $smoothing_kernel by 2.355 (approximately 8*log(2).
    [[ "$smoothing_kernel" == "default" ]] &&
	smoothing_kernel=$(get_default_smoothing "$templateName") &&
        rel "smoothing change from 'default' to '$smoothing_kernal' (for '$templateName' )" c >&2
    [ -z "$smoothing_kernel" -a $no_smooth -eq 0 ] &&
	echo "cannot continue without smoothing kernel" && exit 1

    sigma=$( echo "scale=5; $smoothing_kernel/2.355" | bc )

    #smoothed files include the FHWM as a sufix
    [ $no_smooth -eq 0 ] && smoothing_suffix="_${smoothing_kernel}" || smoothing_suffix=

    if [[ $rmautocorr -eq 1 && $arma_nuisance_regression -eq 0 ]]; then
	rel "-rmautocorr and -ols_nuisance_regression both specified. This is an invalid combination." c
	rel "Switching to ARMA(1,1) for nuisance regression and removing autocorrelation by -Rwherr in 3dREMLfit" c
	arma_nuisance_regression=1
    fi
    
    if [ -n "${logFile}" ]; then
	archive_file "${logFile}" #move any existing files out of the way
	
        #add absolute path to log file location
	logFile="${funcdir}/$( basename $logFile )" ##TODO: make path handling more robust to non-local directories
	
	echo "#!/bin/bash" > "${logFile}"
       echo "## Log of preprocessFunctional commands. started $(date)" >> "${logFile}"
	echo -e "## Call: $thiscommandinfo" >> "${logFile}"
       # add system info
       echo -e "## SYSTEM INFO: $(hostname); fsl $(cat $FSLDIR/etc/fslversion); $(afni -ver); $(antsRegistration --version); py: $(python3 --version); nipy: $(python3 -m pip show nipy|grep Version)" >> "${logFile}"
    fi

    if uname -n | grep -q "comp-hm.*aci.ics.psu.edu"; then
	rel "Running on ACI high-memory cluster. Increase MATLAB RAM limit and force MATLAB single threading." c
	MATLAB_RAM_limit=16
	MATLAB_single_thread="-singleCompThread"
    fi

}

#process command line parameters for preprocessMprage
function parse_mprage_args() {

    USE_OLD_TEMPLATE=
    # NB. defaults here will overwrite those in preprocessMprage
    unifize=0
    deneck=0
    deface=0
    CUT_ZIDX=""

    while [ _$1 != _ ] ; do
	if [[ $1 = -b || $1 = -bet_opts ]] ; then
	    betOpts="${2}"
	    shift 2
	elif [[ $1 = -bright_skull ]] ; then
	    bright_skull=1
	    shift 1
       elif [[ $1 = -check_dependencies ]]; then 
          check_dep_list runROBEX.sh gzip 3dSkullStrip Dimon robustfov fslmaths bet fast applywarp
          exit $?
	elif [[ $1 = -cleanup ]]; then
	    cleanup=1
	    shift 1
	elif [[ $1 = -cleanup_only ]]; then
	    cleanup_only=1
	    shift 1
	elif [[ $1 = -custom_brainmask ]]; then
	    brainmask="${2}"
	    shift 2
	elif [[ $1 = -cut_zindex ]]; then
	    CUT_ZIDX="${2}"
	    shift 2
	elif [[ $1 = -d || $1 = -delete_dicom ]]; then
	    low=$( echo "${2}" | awk '{print tolower($0)}' ) 	#force lower case input
	    if [[ $2 = "delete" || $2 = "yes" || $2 = "no" || $2 = "archive" ]]; then
		delDicom="${low}"
		shift 2
	    elif [[ $2 = "y" || $2 = "n" || $2 = "a" ]]; then
		echo "Use of single character deprecated. Please change to yes, no, archive."
		delDicom="${low}"
		shift 2
	    else
		echo -e "Unrecognized ${1}: ${2}.\n  Options are: ${1} delete yes no archive."
		exit 1
	    fi
       elif [[ $1 = -deface  ]]; then
          # 20210617 remove face (arms and hands near face too)
          deface=1
          shift 1
       elif [[ $1 = -deneck  ]]; then
          # 20210617 remove below neck
          deneck=1
          shift 1
	elif [[ $1 = -p || $1 = -dicom ]]; then
	    dicomPattern="${2}"
	    shift 2
       elif [[ $1 = "-post_bet_skullmask" ]]; then
	    post_bet_skullmask="${2}"
	    shift 2
	elif [[ $1 = -fnirt_mask ]]; then
	    fnirt_mask="${2}"
	    shift 2
	elif [[ $1 = -grad_unwarp ]]; then
	    gcoeffs="${2}"
	    shift 2
	elif [[ $1 = -h || $1 = -help ]]; then
	    printHelp
	    exit 0
	elif [ $1 = -log ]; then
	    logFile="${2}"
	    shift 2
	elif [[ $1 = -no_bias ]]; then
	    biasCorrect=0
	    shift 1
	elif [[ $1 = -n || $1 = -nifti ]]; then
	    nifti="${2}"
	    shift 2
	elif [[ $1 = -no_robustfov ]]; then
	    robustfov=0
	    shift 1
	elif [[ $1 = -o || $1 = -output ]]; then
	    outputFile="${2}"
	    shift 2
	elif [[ $1 = -r || $1 = -template_brain ]]; then
	    reference="${2}"
	    shift 2
	elif [[ $1 = -ss_method ]]; then
	    ssmethod="${2}"
	    shift 2
	elif [[ $1 = -startover ]]; then
           # explicity used in flag file (.preprocessmprage_complete) check
           # needed here only to shift out
	    shift 1
	elif [[ $1 = -strongbias || $1 = -strong_bias ]]; then
	    strongBias=1
	    shift 1
       elif [[ $1 = -use_old_mni  ]]; then
          USE_OLD_TEMPLATE=yes
          shift 1
       elif [[ $1 = -unifize  ]]; then
          # 20210422 use 3dUnifize (implemented for baby data)
          #  remove shading artifacts.
          # The output dataset has the white matter (WM) intensity approximately
          # uniformized across space, and scaled to peak at about 1000.
          unifize=1
          shift 1
	elif [[ $1 = -warpres || $1 = -w ]]; then
	    wr="${2}"
	    if [[ ! ${wr} =~ ^[0-9]+$ ]]; then
		echo "-warpres must be an integer (e.g., 10)."
		exit 1
	    fi
	    shift 2
	elif [[ $1 = -weakbias || $1 = -weak_bias ]]; then
	    strongBias=0
	    shift 1
	else
            printHelp
            echo -e "----------------\n\n"
            echo "Unrecognized command line parameter: ${1}"
            exit 1
	fi
    done

    #explicit return code needed to avoid implicit status of prior command
    return 0

}

# check dependiencies
#  useful for looking for biniaries e.g. fslmaths (fsl), antsRegistrationSyN (ANTs)
#  as well as language modules e.g python:nipy perl:App::AFNI::SiemensPhysio (siemphysdat)
check_dep_list(){
    local missing_deps=0
    for cmd in $@; do
       local module=${cmd#*:} # remove perl: python: or R:
       if [[ $cmd =~ ^python: ]]; then
          python3 -c "import $module;import sys; sys.exit(0)" 2>/dev/null && continue
          # python3 aroma  (v4) is from rtrhd's fork Bristol University CRIC: git+https://github.com/rtrhd/ICA-AROMA
          # using original ica_aroma: git+https://github.com/WillForan/ICA-AROMA.git@maartenmennes-setup.py
          [[ $module == "ica_aroma" ]] && module='git+https://github.com/WillForan/ICA-AROMA.git@maartenmennes-setup.py'
          echo "missing $cmd; consider 'python3 -m pip install --user $module'"  && let ++missing_deps
       elif [[ $cmd =~ ^perl: ]]; then
          perl -M$module -e "exit(0)" 2>/dev/null && continue
          echo "missing $cmd; consider 'cpanm $module'" && let ++missing_deps
       elif [[ $cmd =~ ^R: ]]; then
          Rscript -e "quit(status=as.numeric(!is.element('$module',installed.packages()[,1])),save='no')" && continue
          echo "missing ${cmd}; consider Rscript -e 'install.packages(\"$module\")'" && let ++missing_deps
       else
          command -v $cmd >/dev/null && continue
          echo "missing $cmd" && let ++missing_deps
          case $cmd in
            antsRegistrationSyN.sh) echo "# see https://github.com/stnava/ANTs.git";;
            c3d_affine_tool) echo "# maybe 'apt install convert3d'; www.itksnap.org; http://www.nitrc.org/frs/downloadlink.php/1261";;
            3dcalc|afni) echo "# maybe 'apt install afni'; https://afni.nimh.nih.gov";;
          esac
       fi
    done
    [ $missing_deps -eq 0 ] && echo "$0 has all dependencies met!" 
    return $missing_deps
}

load_func_bids(){
 # try to use BIDS json sidecar for sliceacquisition and tr
 local bids_json bids_tr bids_echo
 bids_json="$1"
 [ ! -r "$bids_json" ] && rel "No bids sidecar '$bids_json' (pwd: '$(pwd)')" c && return
 rel "Using BIDS json sidecar $bids_json!" c
 local bids_tr=$(jq .RepetitionTime < "$bids_json")
 if [ -n "$bids_json" ]; then
    [ -n "$tr" -a "$tr" != "$bids_tr" ] &&
       rel "Overwriting '-tr $tr' to '$bids_tr'" c ||
       rel "setting TR to '$bids_tr' usig bids sidecar '$(pwd)/$bids_json':.RepetitionTime" c
    tr="$bids_tr"
 fi

 # epiTE used for spin echo or gre fieldmap
 # but gre fieldmap probably pulls from config
 # 
 if [ -z "${epiTE:-}" ] ; then
    #global epiTE
    bids_echo="$(jq .EchoTime < "$bids_json")"
    [ -n "$bids_echo" ] &&
       epiTE="$bids_echo" &&
       rel "setting epiTE from bids '$bids_json' => $epiTE seconds" c 
 fi

 # slice timing
 local bids_slice
 bids_slice=$(jq -r '.SliceTiming|@csv'< "$bids_json")
 if [ -z "$bids_slice" ]; then
    rel "ERROR: '$bids_json' does not have SliceTiming?!" c
 fi
 # we do want slice time correction and have bids desc of it
 if [ "${no_st:-0}" -eq 0 ] && [ -n "$bids_slice" ]; then
    local bids_cst="$PWD/.bids_custom_slice.txt"
    echo "$bids_slice" > "$bids_cst"
    echo "$bids_cst" >&2
    cat "$bids_cst" >&2
    if [ -n "$sliceTimesFile" ] || [ -n "$sliceAcquisition" ]; then
       rel "Overwriting slicetime b/c '$bids_json' exists. rm to ignore. File '$sliceTimesFile' or order '$sliceAcquisition' ignored. Now using $bids_cst and 4dmotion!" c
    else
       rel "Setting slice timing to $bids_cst" c
    fi
    sliceTimesFile="$bids_cst"
    sliceMotion4D=1
 fi
 
}

get_default_smoothing() {
  # input either matches [0-9.]+mm$ (functional tempate) or a nifti file
  # smooth size default based on desired resolution.
  # will be overwritten if '-- -smoothing_kernel x' specified
  # find_mprage_warp is from func_template. must be loaded
  local ref=$1
  local res=0
  if [[ $ref =~ _([0-9.]+)mm$ ]]; then
      res=${BASH_REMATCH[1]}
  elif [ -r "$ref" ]; then
      res=$(3dinfo -adi "$ref") # all templates are symetric (2x2x2)
  else
      echo "ERROR: cannot determine what smoothing kernel should be with ref '$ref'" >&2
      return 1
  fi

  local smooth_at=
  case $res in
      2.5*) smooth_at=5;;
      2.3*) smooth_at=5;;
      2*) smooth_at=4;;
      3*) smooth_at=5;;
      *) echo "$FUNCNAME: smoothing size for res '$res' of '$ref' not specified. manually specify like '-smoothing_kernel X' (in mm)" >&2; return 1;;
  esac
  echo "$smooth_at"
}
# vim: set tabstop=7:
