#!/usr/bin/env bash

REMOVE_FIRST_VOLUMES_GLOBALS=(n_rm_firstvols prefix funcFile)

remove_first_volumes() {
  print_vars_in REMOVE_FIRST_VOLUMES_GLOBALS
  # afni is zero based
  # so if we wanted to remove 1 volume (the first)
  # we'd start the new file on index 1
  if [ ! -r .trunc_complete ]; then
    rel "truncating: remove $n_rm_firstvols volumes" c
    rel "3dTcat $prefix$funcFile'[$n_rm_firstvols..$]' -prefix '0$prefix$funcFile'"
    date > .trunc_complete
  fi
  prefix="0$prefix" 
}

# vim: set tabstop=7:
