#!/bin/bash

set -e
[ -z "${remote_host}" ] && echo "Expect remote_host variable to be set in environment" && exit 1

#setup master connection to remote
ls $HOME/.ssh/controlmasters/*WPC-6290* 2>/dev/null 1>/dev/null || ./remote.expect

timestamp=$(date +%Y%m%d_%H%M)

if [[ $# -ne 2 ]]; then
    echo "expect two parameters: <remote source dir> <local target dir>"
    exit 1
fi

src="${1%/}/" #for consistency, remove any trailing slash, then add trailing slash
dest="${2%/}" #destination dir should not have trailing slash!

set -x
rsync --recursive --verbose --perms --times \
    --filter='-p .DS_Store' \
    --filter="- /.DocumentRevisions-V100/" \
    --filter="- /.Spotlight-V100/" \
    --filter="- /.Trashes/" \
    --filter="- /.TemporaryItems/" \
    ${remote_host}:${src} \
    ${dest}
set +x
